// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/command/command.proto

package com.xray.app.proxyman.command;

public final class Command {
    private Command() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AddUserOperation_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AddUserOperation_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_RemoveUserOperation_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_RemoveUserOperation_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AddInboundRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AddInboundRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AddInboundResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AddInboundResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_RemoveInboundRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_RemoveInboundRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_RemoveInboundResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_RemoveInboundResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AlterInboundRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AlterInboundRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AlterInboundResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AlterInboundResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AddOutboundRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AddOutboundRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AddOutboundResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AddOutboundResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_RemoveOutboundRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_RemoveOutboundRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_RemoveOutboundResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_RemoveOutboundResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AlterOutboundRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AlterOutboundRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_AlterOutboundResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_AlterOutboundResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_proxyman_command_Config_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_proxyman_command_Config_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\033xcore/command/command.proto\022\031xray.app." +
                        "proxyman.command\032 xcore/common/protocol/" +
                        "user.proto\032\'xcore/common/serial/typed_me" +
                        "ssage.proto\032\027xcore/core/config.proto\"<\n\020" +
                        "AddUserOperation\022(\n\004user\030\001 \001(\0132\032.xray.co" +
                        "mmon.protocol.User\"$\n\023RemoveUserOperatio" +
                        "n\022\r\n\005email\030\001 \001(\t\"E\n\021AddInboundRequest\0220\n" +
                        "\007inbound\030\001 \001(\0132\037.xray.core.InboundHandle" +
                        "rConfig\"\024\n\022AddInboundResponse\"#\n\024RemoveI" +
                        "nboundRequest\022\013\n\003tag\030\001 \001(\t\"\027\n\025RemoveInbo" +
                        "undResponse\"i\n\023AlterInboundRequest\022\013\n\003ta" +
                        "g\030\001 \001(\t\0223\n\toperation\030\002 \001(\0132 .xray.common" +
                        ".serial.TypedMessage\022\020\n\010password\030\003 \001(\t\"\026" +
                        "\n\024AlterInboundResponse\"H\n\022AddOutboundReq" +
                        "uest\0222\n\010outbound\030\001 \001(\0132 .xray.core.Outbo" +
                        "undHandlerConfig\"\025\n\023AddOutboundResponse\"" +
                        "$\n\025RemoveOutboundRequest\022\013\n\003tag\030\001 \001(\t\"\030\n" +
                        "\026RemoveOutboundResponse\"X\n\024AlterOutbound" +
                        "Request\022\013\n\003tag\030\001 \001(\t\0223\n\toperation\030\002 \001(\0132" +
                        " .xray.common.serial.TypedMessage\"\027\n\025Alt" +
                        "erOutboundResponse\"\010\n\006Config2\305\005\n\016Handler" +
                        "Service\022k\n\nAddInbound\022,.xray.app.proxyma" +
                        "n.command.AddInboundRequest\032-.xray.app.p" +
                        "roxyman.command.AddInboundResponse\"\000\022t\n\r" +
                        "RemoveInbound\022/.xray.app.proxyman.comman" +
                        "d.RemoveInboundRequest\0320.xray.app.proxym" +
                        "an.command.RemoveInboundResponse\"\000\022q\n\014Al" +
                        "terInbound\022..xray.app.proxyman.command.A" +
                        "lterInboundRequest\032/.xray.app.proxyman.c" +
                        "ommand.AlterInboundResponse\"\000\022n\n\013AddOutb" +
                        "ound\022-.xray.app.proxyman.command.AddOutb" +
                        "oundRequest\032..xray.app.proxyman.command." +
                        "AddOutboundResponse\"\000\022w\n\016RemoveOutbound\022" +
                        "0.xray.app.proxyman.command.RemoveOutbou" +
                        "ndRequest\0321.xray.app.proxyman.command.Re" +
                        "moveOutboundResponse\"\000\022t\n\rAlterOutbound\022" +
                        "/.xray.app.proxyman.command.AlterOutboun" +
                        "dRequest\0320.xray.app.proxyman.command.Alt" +
                        "erOutboundResponse\"\000B]\n\035com.xray.app.pro" +
                        "xyman.commandP\001Z\036initon/lib/proxy/xcore/" +
                        "command\252\002\031Xray.App.Proxyman.Commandb\006pro" +
                        "to3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.xray.common.protocol.UserOuterClass.getDescriptor(),
                                com.xray.common.serial.TypedMessageOuterClass.getDescriptor(),
                                com.xray.core.ConfigOuterClass.getDescriptor(),
                        });
        internal_static_xray_app_proxyman_command_AddUserOperation_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_app_proxyman_command_AddUserOperation_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AddUserOperation_descriptor,
                new java.lang.String[]{"User",});
        internal_static_xray_app_proxyman_command_RemoveUserOperation_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_xray_app_proxyman_command_RemoveUserOperation_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_RemoveUserOperation_descriptor,
                new java.lang.String[]{"Email",});
        internal_static_xray_app_proxyman_command_AddInboundRequest_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_xray_app_proxyman_command_AddInboundRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AddInboundRequest_descriptor,
                new java.lang.String[]{"Inbound",});
        internal_static_xray_app_proxyman_command_AddInboundResponse_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_xray_app_proxyman_command_AddInboundResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AddInboundResponse_descriptor,
                new java.lang.String[]{});
        internal_static_xray_app_proxyman_command_RemoveInboundRequest_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_xray_app_proxyman_command_RemoveInboundRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_RemoveInboundRequest_descriptor,
                new java.lang.String[]{"Tag",});
        internal_static_xray_app_proxyman_command_RemoveInboundResponse_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_xray_app_proxyman_command_RemoveInboundResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_RemoveInboundResponse_descriptor,
                new java.lang.String[]{});
        internal_static_xray_app_proxyman_command_AlterInboundRequest_descriptor =
                getDescriptor().getMessageTypes().get(6);
        internal_static_xray_app_proxyman_command_AlterInboundRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AlterInboundRequest_descriptor,
                new java.lang.String[]{"Tag", "Operation", "Password",});
        internal_static_xray_app_proxyman_command_AlterInboundResponse_descriptor =
                getDescriptor().getMessageTypes().get(7);
        internal_static_xray_app_proxyman_command_AlterInboundResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AlterInboundResponse_descriptor,
                new java.lang.String[]{});
        internal_static_xray_app_proxyman_command_AddOutboundRequest_descriptor =
                getDescriptor().getMessageTypes().get(8);
        internal_static_xray_app_proxyman_command_AddOutboundRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AddOutboundRequest_descriptor,
                new java.lang.String[]{"Outbound",});
        internal_static_xray_app_proxyman_command_AddOutboundResponse_descriptor =
                getDescriptor().getMessageTypes().get(9);
        internal_static_xray_app_proxyman_command_AddOutboundResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AddOutboundResponse_descriptor,
                new java.lang.String[]{});
        internal_static_xray_app_proxyman_command_RemoveOutboundRequest_descriptor =
                getDescriptor().getMessageTypes().get(10);
        internal_static_xray_app_proxyman_command_RemoveOutboundRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_RemoveOutboundRequest_descriptor,
                new java.lang.String[]{"Tag",});
        internal_static_xray_app_proxyman_command_RemoveOutboundResponse_descriptor =
                getDescriptor().getMessageTypes().get(11);
        internal_static_xray_app_proxyman_command_RemoveOutboundResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_RemoveOutboundResponse_descriptor,
                new java.lang.String[]{});
        internal_static_xray_app_proxyman_command_AlterOutboundRequest_descriptor =
                getDescriptor().getMessageTypes().get(12);
        internal_static_xray_app_proxyman_command_AlterOutboundRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AlterOutboundRequest_descriptor,
                new java.lang.String[]{"Tag", "Operation",});
        internal_static_xray_app_proxyman_command_AlterOutboundResponse_descriptor =
                getDescriptor().getMessageTypes().get(13);
        internal_static_xray_app_proxyman_command_AlterOutboundResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_AlterOutboundResponse_descriptor,
                new java.lang.String[]{});
        internal_static_xray_app_proxyman_command_Config_descriptor =
                getDescriptor().getMessageTypes().get(14);
        internal_static_xray_app_proxyman_command_Config_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_proxyman_command_Config_descriptor,
                new java.lang.String[]{});
        com.xray.common.protocol.UserOuterClass.getDescriptor();
        com.xray.common.serial.TypedMessageOuterClass.getDescriptor();
        com.xray.core.ConfigOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
