// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/command/command.proto

package com.xray.app.proxyman.command;

public interface RemoveOutboundResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:xray.app.proxyman.command.RemoveOutboundResponse)
        com.google.protobuf.MessageOrBuilder {
}
