// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/stats/command.proto

package com.xray.app.stats.command;

public final class Command {
    private Command() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_GetStatsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_GetStatsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_Stat_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_Stat_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_GetStatsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_GetStatsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_QueryStatsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_QueryStatsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_QueryStatsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_QueryStatsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_SysStatsRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_SysStatsRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_SysStatsResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_SysStatsResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_app_stats_command_Config_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_app_stats_command_Config_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\031xcore/stats/command.proto\022\026xray.app.st" +
                        "ats.command\".\n\017GetStatsRequest\022\014\n\004name\030\001" +
                        " \001(\t\022\r\n\005reset\030\002 \001(\010\"#\n\004Stat\022\014\n\004name\030\001 \001(" +
                        "\t\022\r\n\005value\030\002 \001(\003\">\n\020GetStatsResponse\022*\n\004" +
                        "stat\030\001 \001(\0132\034.xray.app.stats.command.Stat" +
                        "\"3\n\021QueryStatsRequest\022\017\n\007pattern\030\001 \001(\t\022\r" +
                        "\n\005reset\030\002 \001(\010\"@\n\022QueryStatsResponse\022*\n\004s" +
                        "tat\030\001 \003(\0132\034.xray.app.stats.command.Stat\"" +
                        "\021\n\017SysStatsRequest\"\302\001\n\020SysStatsResponse\022" +
                        "\024\n\014NumGoroutine\030\001 \001(\r\022\r\n\005NumGC\030\002 \001(\r\022\r\n\005" +
                        "Alloc\030\003 \001(\004\022\022\n\nTotalAlloc\030\004 \001(\004\022\013\n\003Sys\030\005" +
                        " \001(\004\022\017\n\007Mallocs\030\006 \001(\004\022\r\n\005Frees\030\007 \001(\004\022\023\n\013" +
                        "LiveObjects\030\010 \001(\004\022\024\n\014PauseTotalNs\030\t \001(\004\022" +
                        "\016\n\006Uptime\030\n \001(\r\"\010\n\006Config2\272\002\n\014StatsServi" +
                        "ce\022_\n\010GetStats\022\'.xray.app.stats.command." +
                        "GetStatsRequest\032(.xray.app.stats.command" +
                        ".GetStatsResponse\"\000\022e\n\nQueryStats\022).xray" +
                        ".app.stats.command.QueryStatsRequest\032*.x" +
                        "ray.app.stats.command.QueryStatsResponse" +
                        "\"\000\022b\n\013GetSysStats\022\'.xray.app.stats.comma" +
                        "nd.SysStatsRequest\032(.xray.app.stats.comm" +
                        "and.SysStatsResponse\"\000B]\n\032com.xray.app.s" +
                        "tats.commandP\001Z$initon/lib/proxy/xcore/s" +
                        "tats/command\252\002\026Xray.App.Stats.Commandb\006p" +
                        "roto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_xray_app_stats_command_GetStatsRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_app_stats_command_GetStatsRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_GetStatsRequest_descriptor,
                new java.lang.String[]{"Name", "Reset",});
        internal_static_xray_app_stats_command_Stat_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_xray_app_stats_command_Stat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_Stat_descriptor,
                new java.lang.String[]{"Name", "Value",});
        internal_static_xray_app_stats_command_GetStatsResponse_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_xray_app_stats_command_GetStatsResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_GetStatsResponse_descriptor,
                new java.lang.String[]{"Stat",});
        internal_static_xray_app_stats_command_QueryStatsRequest_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_xray_app_stats_command_QueryStatsRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_QueryStatsRequest_descriptor,
                new java.lang.String[]{"Pattern", "Reset",});
        internal_static_xray_app_stats_command_QueryStatsResponse_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_xray_app_stats_command_QueryStatsResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_QueryStatsResponse_descriptor,
                new java.lang.String[]{"Stat",});
        internal_static_xray_app_stats_command_SysStatsRequest_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_xray_app_stats_command_SysStatsRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_SysStatsRequest_descriptor,
                new java.lang.String[]{});
        internal_static_xray_app_stats_command_SysStatsResponse_descriptor =
                getDescriptor().getMessageTypes().get(6);
        internal_static_xray_app_stats_command_SysStatsResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_SysStatsResponse_descriptor,
                new java.lang.String[]{"NumGoroutine", "NumGC", "Alloc", "TotalAlloc", "Sys", "Mallocs", "Frees", "LiveObjects", "PauseTotalNs", "Uptime",});
        internal_static_xray_app_stats_command_Config_descriptor =
                getDescriptor().getMessageTypes().get(7);
        internal_static_xray_app_stats_command_Config_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_app_stats_command_Config_descriptor,
                new java.lang.String[]{});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
