// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/common/protocol/server_spec.proto

package com.xray.common.protocol;

public final class ServerSpec {
    private ServerSpec() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_common_protocol_ServerEndpoint_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_common_protocol_ServerEndpoint_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\'xcore/common/protocol/server_spec.prot" +
                        "o\022\024xray.common.protocol\032\036xcore/common/ne" +
                        "t/address.proto\032 xcore/common/protocol/u" +
                        "ser.proto\"v\n\016ServerEndpoint\022,\n\007address\030\001" +
                        " \001(\0132\033.xray.common.net.IPOrDomain\022\014\n\004por" +
                        "t\030\002 \001(\r\022(\n\004user\030\003 \003(\0132\032.xray.common.prot" +
                        "ocol.UserB[\n\030com.xray.common.protocolP\001Z" +
                        "&initon/lib/proxy/xcore/common/protocol\252" +
                        "\002\024Xray.Common.Protocolb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.xray.common.net.Address.getDescriptor(),
                                com.xray.common.protocol.UserOuterClass.getDescriptor(),
                        });
        internal_static_xray_common_protocol_ServerEndpoint_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_common_protocol_ServerEndpoint_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_common_protocol_ServerEndpoint_descriptor,
                new java.lang.String[]{"Address", "Port", "User",});
        com.xray.common.net.Address.getDescriptor();
        com.xray.common.protocol.UserOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
