server:
  port: 9002

spring:
  application:
    name: match-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/goalhub_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Bangkok
    username: goalhub
    password: goalhub123456
    driver-class-name: com.mysql.cj.jdbc.Driver