// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/shadowsocks/config.proto

package com.xray.proxy.shadowsocks;

public final class Config {
    private Config() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_proxy_shadowsocks_Account_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_proxy_shadowsocks_Account_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_proxy_shadowsocks_ServerConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_proxy_shadowsocks_ServerConfig_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_proxy_shadowsocks_ClientConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_proxy_shadowsocks_ClientConfig_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\036xcore/shadowsocks/config.proto\022\026xray.p" +
                        "roxy.shadowsocks\032\036xcore/common/net/netwo" +
                        "rk.proto\032 xcore/common/protocol/user.pro" +
                        "to\032\'xcore/common/protocol/server_spec.pr" +
                        "oto\"f\n\007Account\022\020\n\010password\030\001 \001(\t\0227\n\013ciph" +
                        "er_type\030\002 \001(\0162\".xray.proxy.shadowsocks.C" +
                        "ipherType\022\020\n\010iv_check\030\003 \001(\010\"d\n\014ServerCon" +
                        "fig\022)\n\005users\030\001 \003(\0132\032.xray.common.protoco" +
                        "l.User\022)\n\007network\030\002 \003(\0162\030.xray.common.ne" +
                        "t.Network\"D\n\014ClientConfig\0224\n\006server\030\001 \003(" +
                        "\0132$.xray.common.protocol.ServerEndpoint*" +
                        "t\n\nCipherType\022\013\n\007UNKNOWN\020\000\022\017\n\013AES_128_GC" +
                        "M\020\005\022\017\n\013AES_256_GCM\020\006\022\025\n\021CHACHA20_POLY130" +
                        "5\020\007\022\026\n\022XCHACHA20_POLY1305\020\010\022\010\n\004NONE\020\tB[\n" +
                        "\032com.xray.proxy.shadowsocksP\001Z\"initon/li" +
                        "b/proxy/xcore/shadowsocks\252\002\026Xray.Proxy.S" +
                        "hadowsocksb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.xray.common.net.NetworkOuterClass.getDescriptor(),
                                com.xray.common.protocol.UserOuterClass.getDescriptor(),
                                com.xray.common.protocol.ServerSpec.getDescriptor(),
                        });
        internal_static_xray_proxy_shadowsocks_Account_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_proxy_shadowsocks_Account_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_proxy_shadowsocks_Account_descriptor,
                new java.lang.String[]{"Password", "CipherType", "IvCheck",});
        internal_static_xray_proxy_shadowsocks_ServerConfig_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_xray_proxy_shadowsocks_ServerConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_proxy_shadowsocks_ServerConfig_descriptor,
                new java.lang.String[]{"Users", "Network",});
        internal_static_xray_proxy_shadowsocks_ClientConfig_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_xray_proxy_shadowsocks_ClientConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_proxy_shadowsocks_ClientConfig_descriptor,
                new java.lang.String[]{"Server",});
        com.xray.common.net.NetworkOuterClass.getDescriptor();
        com.xray.common.protocol.UserOuterClass.getDescriptor();
        com.xray.common.protocol.ServerSpec.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
