// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/http/config.proto

package com.xray.proxy.http;

public final class Config {
    private Config() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_proxy_http_Account_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_proxy_http_Account_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_proxy_http_ServerConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_proxy_http_ServerConfig_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_proxy_http_ServerConfig_AccountsEntry_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_proxy_http_ServerConfig_AccountsEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_proxy_http_ClientConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_proxy_http_ClientConfig_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\027xcore/http/config.proto\022\017xray.proxy.ht" +
                        "tp\032\'xcore/common/protocol/server_spec.pr" +
                        "oto\"-\n\007Account\022\020\n\010username\030\001 \001(\t\022\020\n\010pass" +
                        "word\030\002 \001(\t\"\302\001\n\014ServerConfig\022\023\n\007timeout\030\001" +
                        " \001(\rB\002\030\001\022=\n\010accounts\030\002 \003(\0132+.xray.proxy." +
                        "http.ServerConfig.AccountsEntry\022\031\n\021allow" +
                        "_transparent\030\003 \001(\010\022\022\n\nuser_level\030\004 \001(\r\032/" +
                        "\n\rAccountsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
                        "\001(\t:\0028\001\"D\n\014ClientConfig\0224\n\006server\030\001 \003(\0132" +
                        "$.xray.common.protocol.ServerEndpointBF\n" +
                        "\023com.xray.proxy.httpP\001Z\033initon/lib/proxy" +
                        "/xcore/http\252\002\017Xray.Proxy.Httpb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.xray.common.protocol.ServerSpec.getDescriptor(),
                        });
        internal_static_xray_proxy_http_Account_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_proxy_http_Account_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_proxy_http_Account_descriptor,
                new java.lang.String[]{"Username", "Password",});
        internal_static_xray_proxy_http_ServerConfig_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_xray_proxy_http_ServerConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_proxy_http_ServerConfig_descriptor,
                new java.lang.String[]{"Timeout", "Accounts", "AllowTransparent", "UserLevel",});
        internal_static_xray_proxy_http_ServerConfig_AccountsEntry_descriptor =
                internal_static_xray_proxy_http_ServerConfig_descriptor.getNestedTypes().get(0);
        internal_static_xray_proxy_http_ServerConfig_AccountsEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_proxy_http_ServerConfig_AccountsEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_xray_proxy_http_ClientConfig_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_xray_proxy_http_ClientConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_proxy_http_ClientConfig_descriptor,
                new java.lang.String[]{"Server",});
        com.xray.common.protocol.ServerSpec.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
