// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/common/net/destination.proto

package com.xray.common.net;

public final class Destination {
    private Destination() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_common_net_Endpoint_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_common_net_Endpoint_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\"xcore/common/net/destination.proto\022\017xr" +
                        "ay.common.net\032\036xcore/common/net/network." +
                        "proto\032\036xcore/common/net/address.proto\"q\n" +
                        "\010Endpoint\022)\n\007network\030\001 \001(\0162\030.xray.common" +
                        ".net.Network\022,\n\007address\030\002 \001(\0132\033.xray.com" +
                        "mon.net.IPOrDomain\022\014\n\004port\030\003 \001(\rBL\n\023com." +
                        "xray.common.netP\001Z!initon/lib/proxy/xcor" +
                        "e/common/net\252\002\017Xray.Common.Netb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.xray.common.net.NetworkOuterClass.getDescriptor(),
                                com.xray.common.net.Address.getDescriptor(),
                        });
        internal_static_xray_common_net_Endpoint_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_common_net_Endpoint_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_common_net_Endpoint_descriptor,
                new java.lang.String[]{"Network", "Address", "Port",});
        com.xray.common.net.NetworkOuterClass.getDescriptor();
        com.xray.common.net.Address.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
