// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/transport/internet/config.proto

package com.xray.transport.internet;

public final class Config {
    private Config() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_transport_internet_TransportConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_transport_internet_TransportConfig_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_transport_internet_StreamConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_transport_internet_StreamConfig_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_transport_internet_ProxyConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_transport_internet_ProxyConfig_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_transport_internet_SocketConfig_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_transport_internet_SocketConfig_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n%xcore/transport/internet/config.proto\022" +
                        "\027xray.transport.internet\032\'xcore/common/s" +
                        "erial/typed_message.proto\"\236\001\n\017TransportC" +
                        "onfig\022@\n\010protocol\030\001 \001(\0162*.xray.transport" +
                        ".internet.TransportProtocolB\002\030\001\022\025\n\rproto" +
                        "col_name\030\003 \001(\t\0222\n\010settings\030\002 \001(\0132 .xray." +
                        "common.serial.TypedMessage\"\301\002\n\014StreamCon" +
                        "fig\022@\n\010protocol\030\001 \001(\0162*.xray.transport.i" +
                        "nternet.TransportProtocolB\002\030\001\022\025\n\rprotoco" +
                        "l_name\030\005 \001(\t\022D\n\022transport_settings\030\002 \003(\013" +
                        "2(.xray.transport.internet.TransportConf" +
                        "ig\022\025\n\rsecurity_type\030\003 \001(\t\022;\n\021security_se" +
                        "ttings\030\004 \003(\0132 .xray.common.serial.TypedM" +
                        "essage\022>\n\017socket_settings\030\006 \001(\0132%.xray.t" +
                        "ransport.internet.SocketConfig\"7\n\013ProxyC" +
                        "onfig\022\013\n\003tag\030\001 \001(\t\022\033\n\023transportLayerProx" +
                        "y\030\002 \001(\010\"\204\003\n\014SocketConfig\022\014\n\004mark\030\001 \001(\005\022\013" +
                        "\n\003tfo\030\002 \001(\005\022@\n\006tproxy\030\003 \001(\01620.xray.trans" +
                        "port.internet.SocketConfig.TProxyMode\022%\n" +
                        "\035receive_original_dest_address\030\004 \001(\010\022\024\n\014" +
                        "bind_address\030\005 \001(\014\022\021\n\tbind_port\030\006 \001(\r\022\035\n" +
                        "\025accept_proxy_protocol\030\007 \001(\010\022@\n\017domain_s" +
                        "trategy\030\010 \001(\0162\'.xray.transport.internet." +
                        "DomainStrategy\022\024\n\014dialer_proxy\030\t \001(\t\022\037\n\027" +
                        "tcp_keep_alive_interval\030\n \001(\005\"/\n\nTProxyM" +
                        "ode\022\007\n\003Off\020\000\022\n\n\006TProxy\020\001\022\014\n\010Redirect\020\002*Z" +
                        "\n\021TransportProtocol\022\007\n\003TCP\020\000\022\007\n\003UDP\020\001\022\010\n" +
                        "\004MKCP\020\002\022\r\n\tWebSocket\020\003\022\010\n\004HTTP\020\004\022\020\n\014Doma" +
                        "inSocket\020\005*A\n\016DomainStrategy\022\t\n\005AS_IS\020\000\022" +
                        "\n\n\006USE_IP\020\001\022\013\n\007USE_IP4\020\002\022\013\n\007USE_IP6\020\003Bd\n" +
                        "\033com.xray.transport.internetP\001Z)initon/l" +
                        "ib/proxy/xcore/transport/internet\252\002\027Xray" +
                        ".Transport.Internetb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.xray.common.serial.TypedMessageOuterClass.getDescriptor(),
                        });
        internal_static_xray_transport_internet_TransportConfig_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_transport_internet_TransportConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_transport_internet_TransportConfig_descriptor,
                new java.lang.String[]{"Protocol", "ProtocolName", "Settings",});
        internal_static_xray_transport_internet_StreamConfig_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_xray_transport_internet_StreamConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_transport_internet_StreamConfig_descriptor,
                new java.lang.String[]{"Protocol", "ProtocolName", "TransportSettings", "SecurityType", "SecuritySettings", "SocketSettings",});
        internal_static_xray_transport_internet_ProxyConfig_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_xray_transport_internet_ProxyConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_transport_internet_ProxyConfig_descriptor,
                new java.lang.String[]{"Tag", "TransportLayerProxy",});
        internal_static_xray_transport_internet_SocketConfig_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_xray_transport_internet_SocketConfig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_transport_internet_SocketConfig_descriptor,
                new java.lang.String[]{"Mark", "Tfo", "Tproxy", "ReceiveOriginalDestAddress", "BindAddress", "BindPort", "AcceptProxyProtocol", "DomainStrategy", "DialerProxy", "TcpKeepAliveInterval",});
        com.xray.common.serial.TypedMessageOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
