// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/transport/internet/config.proto

package com.xray.transport.internet;

public interface SocketConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:xray.transport.internet.SocketConfig)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Mark of the connection. If non-zero, the value will be set to SO_MARK.
     * </pre>
     *
     * <code>int32 mark = 1;</code>
     *
     * @return The mark.
     */
    int getMark();

    /**
     * <pre>
     * TFO is the state of TFO settings.
     * </pre>
     *
     * <code>int32 tfo = 2;</code>
     *
     * @return The tfo.
     */
    int getTfo();

    /**
     * <pre>
     * TProxy is for enabling TProxy socket option.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     *
     * @return The enum numeric value on the wire for tproxy.
     */
    int getTproxyValue();

    /**
     * <pre>
     * TProxy is for enabling TProxy socket option.
     * </pre>
     *
     * <code>.xray.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     *
     * @return The tproxy.
     */
    com.xray.transport.internet.SocketConfig.TProxyMode getTproxy();

    /**
     * <pre>
     * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     * option. This option is for UDP only.
     * </pre>
     *
     * <code>bool receive_original_dest_address = 4;</code>
     *
     * @return The receiveOriginalDestAddress.
     */
    boolean getReceiveOriginalDestAddress();

    /**
     * <code>bytes bind_address = 5;</code>
     *
     * @return The bindAddress.
     */
    com.google.protobuf.ByteString getBindAddress();

    /**
     * <code>uint32 bind_port = 6;</code>
     *
     * @return The bindPort.
     */
    int getBindPort();

    /**
     * <code>bool accept_proxy_protocol = 7;</code>
     *
     * @return The acceptProxyProtocol.
     */
    boolean getAcceptProxyProtocol();

    /**
     * <code>.xray.transport.internet.DomainStrategy domain_strategy = 8;</code>
     *
     * @return The enum numeric value on the wire for domainStrategy.
     */
    int getDomainStrategyValue();

    /**
     * <code>.xray.transport.internet.DomainStrategy domain_strategy = 8;</code>
     *
     * @return The domainStrategy.
     */
    com.xray.transport.internet.DomainStrategy getDomainStrategy();

    /**
     * <code>string dialer_proxy = 9;</code>
     *
     * @return The dialerProxy.
     */
    java.lang.String getDialerProxy();

    /**
     * <code>string dialer_proxy = 9;</code>
     *
     * @return The bytes for dialerProxy.
     */
    com.google.protobuf.ByteString
    getDialerProxyBytes();

    /**
     * <code>int32 tcp_keep_alive_interval = 10;</code>
     *
     * @return The tcpKeepAliveInterval.
     */
    int getTcpKeepAliveInterval();
}
