// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/transport/global/config.proto

package com.xray.transport.global;

public final class ConfigOuterClass {
    private ConfigOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_transport_Config_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_transport_Config_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n#xcore/transport/global/config.proto\022\016x" +
                        "ray.transport\032%xcore/transport/internet/" +
                        "config.proto\"R\n\006Config\022D\n\022transport_sett" +
                        "ings\030\001 \003(\0132(.xray.transport.internet.Tra" +
                        "nsportConfig:\002\030\001B^\n\031com.xray.transport.g" +
                        "lobalP\001Z\'initon/lib/proxy/xcore/transpor" +
                        "t/global\252\002\025Xray.Transport.Globalb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.xray.transport.internet.Config.getDescriptor(),
                        });
        internal_static_xray_transport_Config_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_transport_Config_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_transport_Config_descriptor,
                new java.lang.String[]{"TransportSettings",});
        com.xray.transport.internet.Config.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}