// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcore/common/serial/typed_message.proto

package com.xray.common.serial;

public final class TypedMessageOuterClass {
    private TypedMessageOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_xray_common_serial_TypedMessage_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_xray_common_serial_TypedMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\'xcore/common/serial/typed_message.prot" +
                        "o\022\022xray.common.serial\"+\n\014TypedMessage\022\014\n" +
                        "\004type\030\001 \001(\t\022\r\n\005value\030\002 \001(\014BU\n\026com.xray.c" +
                        "ommon.serialP\001Z$initon/lib/proxy/xcore/c" +
                        "ommon/serial\252\002\022Xray.Common.Serialb\006proto" +
                        "3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_xray_common_serial_TypedMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_xray_common_serial_TypedMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_xray_common_serial_TypedMessage_descriptor,
                new java.lang.String[]{"Type", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
